app/Http/Controllers/Backoffice/Library/BrandController.php
<?php

namespace App\Http\Controllers\Backoffice\Library;

use Illuminate\Http\Request;
use App\Models\Library\Brand;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class BrandController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $keyword = $request->keyword;
            $brands = Brand::where('name', 'like', '%' . $keyword . '%')->orderBy('id', 'desc')->paginate(10);
            return view('pages.backoffice.library.brands.list', [
                'brands' => $brands
            ]);
        }
        return view('pages.backoffice.library.brands.main');
    }
    public function create()
    {
        return view('pages.backoffice.library.brands.input');
    }
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => ['required', 'unique:brands,name']
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('name')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('name')
                ]);
            }
        }
        Brand::create([
            'name' => $request->name
        ]);
        return response()->json([
            'alert' => 'success',
            'message' => 'Brand created.'
        ]);
    }
    public function show(Brand $brand)
    {
        //
    }
    public function edit(Brand $brand)
    {
        return view('pages.backoffice.library.brands.input', [
            'brand' => $brand
        ]);
    }
    public function update(Request $request, Brand $brand)
    {
        $rules = [
            'name' => ['required']
        ];
        if ($request->name != $brand->name) {
            $rules['name'] += [count($rules['name']) => 'unique:brands,name'];
        }
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('name')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('name')
                ]);
            }
        }
        Brand::where('id', $brand->id)->update([
            'name' => $request->name,
        ]);
        return response()->json([
            'alert' => 'success',
            'message' => 'Brand updated.'
        ]);
    }
    public function destroy(Brand $brand)
    {
        $brand->delete();
        return response()->json([
            'alert' => 'success',
            'message' => 'Brand deleted.'
        ]);
    }
}

app/Http/Controllers/Backoffice/Library/DiscountController.php
<?php

namespace App\Http\Controllers\Backoffice\Library;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Models\Library\Discount;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class DiscountController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $keyword = $request->keyword;
            $discounts = Discount::where('name', 'like', '%' . $keyword . '%')->orderBy('id', 'desc')->paginate(10);
            return view('pages.backoffice.library.discounts.list', [
                'discounts' => $discounts
            ]);
        }
        return view('pages.backoffice.library.discounts.main');
    }
    public function create()
    {
        return view('pages.backoffice.library.discounts.input');
    }
    public function store(Request $request)
    {
        $rules = [
            'name' => ['required', 'unique:discounts,name'],
            'amount' => ['required', 'numeric'],
            'type' => [Rule::in(['%'])]
        ];
        if ($request->type ?? false) {
            $rules['amount'] += [count($rules['amount']) => 'min:1'];
            $rules['amount'] += [count($rules['amount']) => 'max:100'];
        } else {
            $rules['amount'] += [count($rules['amount']) => 'min:1'];
            $rules['amount'] += [count($rules['amount']) => 'max:99999999'];
        }
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('name')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('name')
                ]);
            }
            if ($errors->has('amount')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('amount')
                ]);
            }
            if ($errors->has('type')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('type')
                ]);
            }
        }
        Discount::create([
            'name' => $request->name,
            'amount' => $request->amount,
            'type' => $request->type ?? false ? $request->type : 'Rp',
        ]);
        return response()->json([
            'alert' => 'success',
            'message' => 'Discount created.'
        ]);
    }
    public function show(Discount $discount)
    {
        //
    }
    public function edit(Discount $discount)
    {
        return view('pages.backoffice.library.discounts.input', [
            'discount' => $discount,
        ]);
    }
    public function update(Request $request, Discount $discount)
    {
        $rules = [
            'name' => ['required'],
            'amount' => ['required', 'numeric'],
            'type' => [Rule::in(['%'])]
        ];
        if ($request->name != $discount->name) {
            $rules['name'] += [count($rules['name']) => 'unique:discounts,name'];
        }
        if ($request->type ?? false) {
            $rules['amount'] += [count($rules['amount']) => 'min:1'];
            $rules['amount'] += [count($rules['amount']) => 'max:100'];
        } else {
            $rules['amount'] += [count($rules['amount']) => 'min:1'];
            $rules['amount'] += [count($rules['amount']) => 'max:99999999'];
        }
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('name')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('name')
                ]);
            }
            if ($errors->has('amount')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('amount')
                ]);
            }
            if ($errors->has('type')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('type')
                ]);
            }
        }
        Discount::where('id', $discount->id)->update([
            'name' => $request->name,
            'amount' => $request->amount,
            'type' => $request->type ?? false ? $request->type : 'Rp',
        ]);
        return response()->json([
            'alert' => 'success',
            'message' => 'Discount updated.'
        ]);
    }
    public function destroy(Discount $discount)
    {
        $discount->delete();
        return response()->json([
            'alert' => 'success',
            'message' => 'Discount deleted.'
        ]);
    }
}

app/Http/Controllers/Backoffice/Library/GratuityController.php
<?php

namespace App\Http\Controllers\Backoffice\Library;

use Illuminate\Http\Request;
use App\Models\Library\Gratuity;
use App\Models\Library\SalesType;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class GratuityController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $keyword = $request->keyword;
            $gratuities = Gratuity::where('name', 'like', '%' . $keyword . '%')->orderBy('id', 'desc')->paginate(10);
            return view('pages.backoffice.library.gratuity.list', [
                'gratuities' => $gratuities
            ]);
        }
        return view('pages.backoffice.library.gratuity.main');
    }
    public function create()
    {
        return view('pages.backoffice.library.gratuity.input');
    }
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => ['required', 'unique:gratuity,name'],
            'amount' => ['required', 'numeric', 'min:1', 'max:100'],
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('name')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('name')
                ]);
            }
            if ($errors->has('amount')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('amount')
                ]);
            }
        }
        Gratuity::create([
            'name' => $request->name,
            'amount' => $request->amount,
        ]);
        return response()->json([
            'alert' => 'success',
            'message' => 'Gratuity created.'
        ]);
    }
    public function show(Gratuity $gratuity)
    {
        //
    }
    public function edit(Gratuity $gratuity)
    {
        return view('pages.backoffice.library.gratuity.input', [
            'gratuity' => $gratuity
        ]);
    }
    public function update(Request $request, Gratuity $gratuity)
    {
        $rules = [
            'name' => ['required'],
            'amount' => ['required', 'numeric', 'min:1', 'max:100'],
        ];
        if ($request->name != $gratuity->name) {
            $rules['name'] += [count($rules['name']) => 'unique:gratuity,name'];
        }
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('name')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('name')
                ]);
            }
            if ($errors->has('amount')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('amount')
                ]);
            }
        }
        Gratuity::where('id', $gratuity->id)->update([
            'name' => $request->name,
            'amount' => $request->amount
        ]);
        return response()->json([
            'alert' => 'success',
            'message' => 'Gratuity updated.'
        ]);
    }
    public function destroy(Gratuity $gratuity)
    {
        foreach (SalesType::whereJsonContains('gratuity_applied', $gratuity->id)->get() as $salesType) {
            $salesType->gratuity_applied->forget($salesType->gratuity_applied->search($gratuity->id));
            $salesType->save();
        }
        $gratuity->delete();
        return response()->json([
            'alert' => 'success',
            'message' => 'Gratuity deleted.'
        ]);
    }
}

app/Http/Controllers/Backoffice/Library/ItemCategoryController.php
<?php

namespace App\Http\Controllers\Backoffice\Library;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Library\ItemCategory;
use Illuminate\Support\Facades\Validator;

class ItemCategoryController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $keyword = $request->keyword;
            $categories = ItemCategory::where('name', 'like', '%' . $keyword . '%')->orderBy('id', 'desc')->paginate(10);
            return view('pages.backoffice.library.categories.list', [
                'categories' => $categories,
            ]);
        }
        return view('pages.backoffice.library.categories.main');
    }
    public function create()
    {
        return view('pages.backoffice.library.categories.input');
    }
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => ['required', 'unique:item_categories,name'],
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('name')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('name')
                ]);
            }
        }
        ItemCategory::create([
            'name' => $request->name,
        ]);
        return response()->json([
            'alert' => 'success',
            'message' => 'Category created.',
        ]);
    }
    public function show(ItemCategory $category)
    {
        //
    }
    public function edit(ItemCategory $category)
    {
        return view('pages.backoffice.library.categories.input', [
            'category' => $category,
        ]);
    }
    public function update(Request $request, ItemCategory $category)
    {
        $rules = [
            'name' => ['required']
        ];
        if ($request->name != $category->name) {
            $rules['name'] += [count($rules['name']) => 'unique:item_categories,name'];
        }
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('name')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('name'),
                ]);
            }
        }
        ItemCategory::where('id', $category->id)->update([
            'name' => $request->name
        ]);
        return response()->json([
            'alert' => 'success',
            'message' => 'Category updated.',
        ]);
    }
    public function destroy(ItemCategory $category)
    {
        $category->delete();
        return response()->json([
            'alert' => 'success',
            'message' => 'Category deleted.',
        ]);
    }
    public function export()
    {
        //
    }
    public function assign(Request $request, ItemCategory $categoy)
    {
        //
    }
}

app/Http/Controllers/Backoffice/Library/ItemLibraryController.php
<?php

namespace App\Http\Controllers\Backoffice\Library;

use App\Http\Controllers\Controller;
use App\Models\Library\Brand;
use App\Models\Library\Item;
use App\Models\Library\ItemCategory;
use Illuminate\Http\Request;

class ItemLibraryController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return view('pages.backoffice.library.item.list');
        }
        return view('pages.backoffice.library.item.main');
    }
    public function create()
    {
        return view('pages.backoffice.library.item.input', [
            'categories' => ItemCategory::orderBy('name', 'asc')->get(),
            'brands' => Brand::orderBy('name', 'asc')->get()
        ]);
    }
    public function store(Request $request)
    {
        //
    }
    public function show(Item $item)
    {
        //
    }
    public function edit(Item $item)
    {
        return view('pages.backoffice.library.item.input', [
            'categories' => ItemCategory::orderBy('name', 'asc')->get(),
        ]);
    }
    public function update(Request $request, Item $item)
    {
        //
    }
    public function destroy(Item $item)
    {
        //
    }
    public function export()
    {
        //
    }
}

app/Http/Controllers/Backoffice/Library/ModifierController.php
<?php

namespace App\Http\Controllers\Backoffice\Library;

use App\Http\Controllers\Controller;
use App\Models\Library\Modifier;
use Illuminate\Http\Request;

class ModifierController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $keyword = $request->keyword;
            $collection = Modifier::where('name', 'like', '%' . $keyword . '%')->orderBy('id', 'desc')->paginate(10);
            return view('pages.backoffice.library.modifier.list', [
                'collection' => $collection
            ]);
        }
        return view('pages.backoffice.library.modifier.main');
    }
    public function create()
    {
        return view('pages.backoffice.library.modifier.input');
    }
    public function store(Request $request)
    {
        //
    }
    public function show(Modifier $modifier)
    {
        return view('pages.backoffice.library.modifier.show',['data' => $modifier]);
    }
    public function edit(Modifier $modifier)
    {
        return view('pages.backoffice.library.modifier.input',['data' => $modifier]);
    }
    public function update(Request $request, Modifier $modifier)
    {
        //
    }
    public function destroy(Modifier $modifier)
    {
        //
    }
}

app/View/Components/BackofficeLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class BackofficeLayout extends Component
{
    public $title;
    public function __construct($title)
    {
        $this->title = $title;
    }
    public function render()
    {
        return view('themes.backoffice.main');
    }
}

app/View/Components/OfficeLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class OfficeLayout extends Component
{
    public $title;
    public function __construct($title)
    {
        $this->title = $title;
    }
    public function render()
    {
        return view('themes.office.main');
    }
}

resources/views/pages/backoffice/library/categories/input.blade.php
<div class="card">
    <div class="card-header border-0 pt-6" id="input_header">
        <h3>
            {{ $category ?? false ? 'Edit' : 'Create' }} Category
        </h3>
    </div>
    <div class="card-body pt-0">
        <form id="form_input">
            <div class="scroll-y me-n7 pe-7" id="konten_input" data-kt-scroll="true"
                data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-max-height="auto"
                data-kt-scroll-dependencies="#input_header" data-kt-scroll-wrappers="#konten_input"
                data-kt-scroll-offset="300px">
                <div class="fv-row mb-7">
                    <label class="required fs-6 fw-bold mb-2">Category Name</label>
                    <input type="text" class="form-control form-control-solid" placeholder="" name="name"
                        value="{{ $category->id ?? false ? $category->name : '' }}" />
                </div>
            </div>
        </form>
    </div>
    <div class="card-footer">
        @if ($category ?? false)
        <button type="button" class="btn btn-danger float-left"
            onclick="handle_confirm('Are you sure?','Yes','No','DELETE','{{route('backoffice.library.categories.destroy',$category->id)}}');">Delete</button>
        @endif
        <button id="btn-save" type="button" class="btn btn-primary" style="float:right;"
            onclick="handle_save('#btn-save', '#form_input', '{{ $category ?? false ? route('backoffice.library.categories.update', $category->id) : route('backoffice.library.categories.store')}}', '{{ $category ?? false ? 'PATCH' : 'POST' }}');">
            Save
        </button>
        <button type="button" class="btn btn-dark me-5" style="float:right;" onclick="load_list(1);">Back</button>
    </div>
</div>

resources/views/pages/backoffice/library/categories/list.blade.php
<table class="table align-middle table-row-dashed fs-6 gy-5" id="table">
    <thead>
        <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
            <th class="min-w-125px">Categories Name</th>
            <th class="min-w-125px">Item Stock</th>
            <th class="text-end min-w-70px"></th>
        </tr>
    </thead>
    <tbody class="fw-bold text-gray-600">
        @foreach ($categories as $category)
        <tr>
            <td>{{ $category->name }}</td>
            <td>0</td>
            <td class="text-end">
                <div class="btn-group" role="group">
                    <button id="action" type="button" class="btn btn-sm btn-light btn-active-light-primary"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Action
                        <span class="svg-icon svg-icon-5 m-0">
                            <span class="svg-icon svg-icon-5 m-0">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                    fill="none">
                                    <path
                                        d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z"
                                        fill="currentColor" />
                                </svg>
                            </span>
                        </span>
                    </button>
                    <div class="dropdown-menu menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-125px py-4"
                        aria-labelledby="action">
                        <div class="menu-item px-3">
                            <a href="javascript:;" class="menu-link px-3">Assign</a>
                        </div>
                        <div class="menu-item px-3">
                            <a href="javascript:;" class="menu-link px-3"
                                onclick="load_input('{{route('backoffice.library.categories.edit',$category->id)}}');">Edit</a>
                        </div>
                        <div class="menu-item px-3">
                            <a href="javascript:;" class="menu-link px-3"
                                onclick="handle_confirm('Are you sure?','Yes','No','DELETE','{{route('backoffice.library.categories.destroy',$category->id)}}');">Delete</a>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
{{$categories->links('themes.backoffice.pagination')}}

resources/views/pages/backoffice/library/categories/main.blade.php
<x-backoffice-layout title="Categories">
    @section('toolbar_title')
    <div data-kt-swapper="true" data-kt-swapper-mode="prepend"
        data-kt-swapper-parent="{default: '#kt_content_container', 'lg': '#kt_toolbar_container'}"
        class="page-title d-flex align-items-center flex-wrap me-3 mb-5 mb-lg-0">
        <!--begin::Title-->
        <h1 class="d-flex text-white fw-bolder fs-3 align-items-center my-1">
            Categories
        </h1>
        <!--end::Title-->
        <!--begin::Separator-->
        <span class="h-20px border-white border-start mx-4"></span>
        <!--end::Separator-->
        <!--begin::Breadcrumb-->
        <ul class="breadcrumb breadcrumb-separatorless fw-bold fs-7 my-1">
            <!--begin::Item-->
            <li class="breadcrumb-item text-white">
                <a href="" class="text-white text-hover-primary">Dashboard</a>
            </li>
            <!--end::Item-->
            <!--begin::Item-->
            <li class="breadcrumb-item">
                <span class="bullet bg-white w-5px h-2px"></span>
            </li>
            <!--end::Item-->
            <!--begin::Item-->
            <li class="breadcrumb-item text-white">Library</li>
            <!--end::Item-->
            <!--begin::Item-->
            <li class="breadcrumb-item">
                <span class="bullet bg-white w-5px h-2px"></span>
            </li>
            <!--end::Item-->
            <!--begin::Item-->
            <li class="breadcrumb-item text-white">Categories</li>
            <!--end::Item-->
        </ul>
        <!--end::Breadcrumb-->
    </div>
    @endsection
    <div class="post d-flex flex-column-fluid" id="kt_post">
        <!--begin::Container-->
        <div id="kt_content_container" class="container-xxl">
            <div class="row">
                <div id="content_list" class="col-lg-5">
                    <!--begin::Card-->
                    <div class="card">
                        <form id="content_filter">
                            @csrf
                            <!--begin::Card header-->
                            <div class="card-header border-0 pt-6">
                                <!--begin::Card title-->
                                <div class="card-title">
                                    <div class="position-relative my-1 me-3">
                                        <select name="outlet_id" class="form-select form-select-solid fw-bolder"
                                            disabled>
                                            <option value="" selected>Outlet 1</option>
                                        </select>
                                    </div>
                                    <div class="d-flex align-items-center position-relative my-1">
                                        <!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
                                        <span class="svg-icon svg-icon-1 position-absolute ms-6">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                viewBox="0 0 24 24" fill="none">
                                                <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2"
                                                    rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor" />
                                                <path
                                                    d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z"
                                                    fill="currentColor" />
                                            </svg>
                                        </span>
                                        <!--end::Svg Icon-->
                                        <input type="text" class="form-control form-control-solid w-250px ps-15"
                                            placeholder="Search" name="keyword" onkeyup="load_list(1);" />
                                    </div>
                                </div>
                                <!--begin::Card title-->
                                <!--begin::Card toolbar-->
                                <div class="card-toolbar">
                                    <!--begin::Toolbar-->
                                    <div class="d-flex justify-content-end" data-kt-customer-table-toolbar="base">
                                        <!--begin::Create Category-->
                                        <button type="button" class="btn btn-primary"
                                            onclick="load_input('{{route('backoffice.library.categories.create')}}');">
                                            Create Category
                                        </button>
                                        <!--end::Create Category-->
                                    </div>
                                    <!--end::Toolbar-->
                                </div>
                                <!--end::Card toolbar-->
                            </div>
                            <!--end::Card header-->
                        </form>
                        <!--begin::Card body-->
                        <div class="card-body pt-0">
                            <!--begin::Table-->
                            <div class="table-responsive">
                                <div id="list_result"></div>
                            </div>
                            <!--end::Table-->
                        </div>
                        <!--end::Card body-->
                    </div>
                    <!--end::Card-->
                </div>
                <div id="content_input" class="col-lg-7"></div>
            </div>
        </div>
        <!--end::Container-->
    </div>
    @section('custom_js')
    <script>
        load_list(1);
    </script>
    @endsection
</x-backoffice-layout>